### ISSUE TITLE
Use of binary prefix

### ISSUE THREAD

**Issue by Dendraspis** [Patman86/x265-Mod-by-Patman#1]
Hello @Patman86 ,

may I suggest using the correct binary prefix as shown here:
https://en.wikipedia.org/wiki/Binary_prefix#Adoption_by_IEC,_NIST_and_ISO
https://de.wikipedia.org/wiki/Bin%C3%A4rpr%C3%A4fix#IEC-Pr%C3%A4fixe_zur_Basis_2

As I saw `Ki` and `Mi` would be the appropriate prefixes instead of `K`and `M` because the bytes are divided by 1024:

https://github.com/Patman86/x265-Mod-by-Patman/blob/7de4be112d7822b3bbfcb22715894a8b020f3b08/source/x265cli.cpp#L443-L472

On the other side using `KB``and `MB` would be better, when values would be divided by 1000.  😁 

I'm glad you created these repositories.  👍   😄

**Comment by Patman86** [comment]
I'll fix that.

But pls have a look [here](https://en.m.wikipedia.org/wiki/Kilobyte)

**Comment by Dendraspis** [comment]
You mean that KB, MB, GB can be used for both?
Yeah, this is probaby why Windows uses it and why it's so confusing sometimes. But meanwhile more and more apps and OSs switch to the IEC definition as far as I read.

It's not that important, but I had to make this suggestion after I checked if it's MB or MiB what I see. 😁

**Comment by Patman86** [comment]
StaxRip itself uses

https://github.com/staxrip/staxrip/blob/462b19e0c320a2eb80488ebbbbdcff1f7014f8b1/Forms/MainForm.vb#L2840

**Comment by Dendraspis** [comment]
@Patman86 
🤣   Guess who wrote this particular line a few months ago.  😁  👍   🤣 

There is no problem using 1024 steps, but then the units should be `KiB`, `MiB`, ...
If you want to use `MiB` thats absolutely okay, but I suggest using the binary prefix instead - so just adding some `i` to the code.  😁 

But yes, it feels like I should change that and use `\ 1000` and `GB` instead.  🤔 

*I hope we are talking (still) about the same thing.*  🤔

**Comment by Patman86** [comment]
I will adhere to the IEC and adopt the recommendations.

**Comment by Dendraspis** [comment]
Thanks.  😊 

> StaxRip itself uses
> https://github.com/staxrip/staxrip/blob/462b19e0c320a2eb80488ebbbbdcff1f7014f8b1/Forms/MainForm.vb#L2840

Just for the sake of completeness:  😉 
https://github.com/staxrip/staxrip/commit/88acb9c5dcb22ead9c838265fa337f3722ea6d17

**Comment by Patman86** [comment]
DONE
[Adjustments to match the SI prefix according to IEC @ ddd9c3f](https://github.com/Patman86/x265-Mod-by-Patman/commit/751211e1e44270518fe3b75dc71b66675c23dc70)
