### ISSUE TITLE
Log entry for AQ mode?

### ISSUE THREAD

**Issue by Boulder08** [Patman86/x265-Mod-by-Patman#11]
Would it be possible to get a csv (per frame) or the encoding log (percentage of all frames) entry for the selected AQ modes when auto AQ is enabled?

**Comment by Patman86** [comment]
I'll see what I can do there, comes then possibly with the next release.

**Comment by Patman86** [comment]
Where do you get the AQ Mode Auto from? You can choose between 6 different parameters, AQ Mode 0 to AQ Mode 5, and these are also displayed as a log during encoding.

**Comment by Boulder08** [comment]
Hmm.. for some reason, I thought jpsdr's x265 mod was based on yours with some features added but the automatic AQ mode selection was already in yours (since it's a quite old mod).

https://github.com/jpsdr/x265/tree/x265_mod

**Comment by Patman86** [comment]
This was put in by jpsdr and is not from my mod. See

[link](https://github.com/jpsdr/x265/commit/5f5ca0c8156fba1abf970b02a7b91b318d6fb1bd)

The AQ mode is also displayed in the log during encoding.

**Comment by Boulder08** [comment]
Ah, ok, it must be from some other mod then :) Yes, the value is in the log, but it's just the default value since it can change per each frame in the automatic mode. jpsdr himself mentioned that he doesn't have the time to add a functionality for that.

**Comment by Patman86** [comment]
Then I'm sorry to disappoint you as well, because I will not be incorporating this change into my mod. Sorry

**Comment by Boulder08** [comment]
Hey, no worries there :)
