### ISSUE TITLE
x64-bit

### ISSUE THREAD

**Issue by Andrasolin** [Patman86/x265-Mod-by-Patman#14]
how to enable this mode? --- StaxRip software

QTGMC and interframe have become more efficient when processing UHD

![изображение](https://github.com/Patman86/x265-Mod-by-Patman/assets/150133906/5b99ca7d-310e-47c4-8e41-9cd3ea166c63)

**Comment by Patman86** [comment]
StaxRip is a GUI based on x64. All tools and filters are 64bit builds. Not necessary too choose these option.
