### ISSUE TITLE
Update compile :)

### ISSUE THREAD

**Issue by tormento** [Patman86/x265-Mod-by-Patman#16]
Would you wish us a Merry Xmas with a new compile? ;)

Thanks in advance!

**Comment by Patman86** [comment]
Hello Tormento.
I'm currently rebuilding my PC, so it's going to be a bit complicated. I would like to provide you with the latest version of all my tools at the turn of the year. Is that okay?

**Comment by tormento** [comment]
@Patman86 of course! It's always a favour that you make us all to compile a new build. Remember my poor Sandy Bridge too!

Have a nice xmas and a great new year!
