### ISSUE TITLE
Add --auto-aq patch

### ISSUE THREAD

**Issue by tormento** [Patman86/x265-Mod-by-Patman#19]
Would you please add the --auto-aq patch?

I'd like to ask for this feature in StaxRip but they couldn't having a proper build :)

**Comment by Patman86** [comment]
I'll apply the patch and update all tools at the beginning of March

**Comment by tormento** [comment]
Please have a look [here](https://github.com/staxrip/staxrip/issues/1241).

**Comment by tormento** [comment]
Just a test update with the different aq-modes with anime content:

![Vinland](https://github.com/Patman86/x265-Mod-by-Patman/assets/2351785/9196bfd6-4632-4699-8c65-d48adab0b43a)

![VinlandPSNR](https://github.com/Patman86/x265-Mod-by-Patman/assets/2351785/384aa4ff-2ff5-4972-8d8c-44f358b7d49a)

![VinlandSSIM](https://github.com/Patman86/x265-Mod-by-Patman/assets/2351785/a553862f-bf4a-4613-9753-97fbdc214990)

![VinlandVMAF](https://github.com/Patman86/x265-Mod-by-Patman/assets/2351785/021daeb5-3e17-49db-8d96-88581a8bef63)
