### ISSUE TITLE
Update to v3.5 FINAL ?

### ISSUE THREAD

**Issue by Dendraspis** [Patman86/x265-Mod-by-Patman#2]
Hey @Patman86 ,

are you going to update your code to [v3.5 FINAL](https://bitbucket.org/multicoreware/x265_git/commits/) in the near future?  😃

**Comment by Patman86** [comment]
Yes, today at the latest tomorrow.

**Comment by Dendraspis** [comment]
Sounds good, I can't live without your cosmetic changes.  😁

**Comment by ghost** [comment]
Any news, @Patman86 I know you're a Dad more than once, but we need this one if you can spare some time, please 😁

**Comment by Patman86** [comment]
I know that you are addictive for this! I will make you a new version tomorrow, promised 😉

**Comment by Patman86** [comment]
I know that you are addictive for this! I will make you a new version tomorrow, promised 😉

**Comment by Patman86** [comment]
I know that you are addictive for this! I will make you a new version tomorrow, promised 😉

**Comment by Patman86** [comment]
DONE, but tagging went wrong 🤦‍♂️
Version is tagged as 3.5+9+14 but it should be 3.5+8+15...

@Dendraspis have a look at commit 7cc02345c2752bd2a06a71e3d01504e742b1e042 (info text)

**Comment by Dendraspis** [comment]
Thanks.  🙂 
And you are really sure you don't want to fix the version number? 😉 

Do you mean the log levels, that now all have the same size? 😎  👍   Very nice idea, indeed!

**Comment by ghost** [comment]
Thanks for the good work @Patman86 !!

Next Staxrip release will most probably be v2.2.0 a major release version, and although version number does not affect the actual process, it may be seen as sloppy in a major release to have a wrong version number displayed in the output text. So I add my vote to @Dendraspis to fix it !! please 🙏🏼 😊

**Comment by Patman86** [comment]
I will correct the version number at the weekend. I hope you can wait that long 😁

@Dendraspis yes, I mean the log level info

**Comment by Dendraspis** [comment]
Regarding your last announcements:  so you mean if I can wait till Monday?  😜  🤐 
The plan was to release it tomorrow evening, but I think we can wait a bit.  😁

**Comment by Patman86** [comment]
I'll do my best and try to correct that tonight, by the weekend at the latest.

I'll change the log info text for x264 too

**Comment by Dendraspis** [comment]
We still have some ugly bugy, so weekend is enough.  😊

**Comment by Patman86** [comment]
I've been researching the tagging process for some time and my version tagging is correct. The version tagging from the source is incorrect. I will report it.

**Comment by Dendraspis** [comment]
@Patman86 
Sounds good.  🙂    And who missed to bump the version?  😁 

Beside that I have a little question to you and probably it's just a cosmetic thing or so, but it makes me curious, even it does not make any difference.
You get these outputs when you select a `--output-depth` of

- 12:  `x265 [INFO]: build info [Windows][GCC 10.2.0][64 bit] 12bit`
- 10:  `x265 [INFO]: build info [Windows][GCC 10.2.0][64 bit] 10bit`
- 8:  `x265 [INFO]: build info [Windows][GCC 10.2.0][64 bit] 8bit+10bit+12bit`

Why does only **8bit** provide, that this build can handle all bit depths?

**Comment by Patman86** [comment]
This is because the version with 8 bit depth forms the basis and the 10 bit and 12 bit are only linked (library). They are not stand-alone binaries.

test this one...

[x265-test.zip](https://github.com/Patman86/x265-Mod-by-Patman/files/6208264/x265-test.zip)

**Comment by ghost** [comment]
> I've been researching the tagging process for some time and my version tagging is correct. The version tagging from the source is incorrect. I will report it.

I remember same thing happened once, maybe 1 year ago or so... The error was from the source...

**Comment by Dendraspis** [comment]
@Patman86 
Thanks for the answer and the binary, which was not necessary as it was just a question to enlighten my knowledge.

@44vince44 
This was also my first thought. 😎

**Comment by Patman86** [comment]
The test version shows everything correctly when you use command `x265.exe -V`, the selected bit depth is only displayed when encoding. I can also look again that I get it adjusted so that all bit depths are always displayed

**Comment by Dendraspis** [comment]
Your official release does it already. 🤔 
```
x265 [INFO]: HEVC encoder version 3.5+9+14-6c69ed37d [Mod by Patman]
x265 [INFO]: build info [Windows][GCC 10.2.0][64 bit] 8bit+10bit+12bit
x265 [INFO]: using cpu capabilities: MMX2 SSE2Fast LZCNT SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
```

Like I said, there is no need to change that behavior from my side. We know the system (now) and we know, that everything works.  👍
