### ISSUE TITLE
Error when using --auto-aq parameters

### ISSUE THREAD

**Issue by tormento** [Patman86/x265-Mod-by-Patman#23]
I have the following error when adding parameters to `--auto-aq`, i.e. `--auto-aq 10`.

D:\Eseguibili\Media\StaxRip\Apps\Encoders\x265\x265.exe **--crf 20 --preset slow --output-depth 10 --keyint 24 --colorprim bt709 --colormatrix bt709 --transfer bt709 --range limited --qpfile** "M:\In\Vinland saga ~BDJP\02 ~847p\11 aqauto 10.qp" **--auto-aq 10 --output** "M:\In\Vinland saga ~BDJP\02 ~847p\11 aqauto 10_temp\11 aqauto 10_out.hevc" "M:\In\Vinland saga ~BDJP\02 ~847p\11 aqauto 10_temp\11 aqauto 10.avs"

x265 [FLAW]: M:\In\Vinland saga ~BDJP\02 ~847p\11 aqauto 10.qp qpfile not found or error in opening qp file
x265 [WARN]: extra unused command arguments given <M:\In\Vinland saga ~BDJP\02 ~847p\11 aqauto 10_temp\11 aqauto 10.avs>

**Comment by Patman86** [comment]
I have not adopted the auto-aq function of JPSDR. My implemented version does not use any additional parameters.

**Comment by Hellboy00000** [comment]
Why did you decide not to use any additional parameters? Is better?

**Comment by tormento** [comment]
That's a pity.

**Comment by Patman86** [comment]
Do the additional parameters in auto-aq mode bring so much added value?

The original form of the patch does not provide any additional parameters. https://gist.github.com/Nomis101/9953a2feb69e9f4b96a73fabca2d5ff8

**Comment by tormento** [comment]
> Do the additional parameters in auto-aq mode bring so much added value?

AFAIK one of the big streaming service employers ( NDA mode on ;) ) use them extensively for the Prime Video, together with `--aq-strength-edge` `--aq-strength-edge` and `--aq-bias-strength-edge`.

I was told that the Media Autobuild Suit and jpsdr builds provide those switches and options.

The syntax for the --auto-aq mode is:

```
--aq-auto    Configure auto-AQ mode. Disabled 0 (default), <>0 enabled
                - Bit 1: If set to 1, enable hysteresis.
                - Bit 2: If set to 1, enable HDR mode => don't use biased mode on auto-AQ.
                - Bit 3: If set to 1, replace AQ-MODE 1 by AQ-MODE 5. Overrided by bit 2.
```

**Comment by Patman86** [comment]
Which Media Autobuild Suite? m-ab-s?

**Comment by tormento** [comment]
I think that's [it](https://github.com/m-ab-s/media-autobuild_suite), not some fork.

Anyway, I tested jpsdr build too and the autoaq results (with auto-aq 10, the most used for SDR material) are worse (a noticeble amount) than yours.

At least that what's FFMetrics VMAF tells.

That's curious, as it's curious that your different builds give different results.

**Comment by Patman86** [comment]
That's really strange that the different versions of my build also deliver different results... What do the results look like with the DJATOM or JPSDR builds, for example, what are the measured values with FFMetrics there? Which build you use now is of course up to you. I still find my simple auto-aq implementation easier to handle. Thanks for your feedback!

**Comment by L4cache** [comment]
> > Do the additional parameters in auto-aq mode bring so much added value?
> 
> AFAIK one of the big streaming service employers ( NDA mode on ;) ) use them extensively for the Prime Video, together with `--aq-strength-edge` `--aq-strength-edge` and `--aq-bias-strength-edge`.
> 
> I was told that the Media Autobuild Suit and jpsdr builds provide those switches and options.
> 
> The syntax for the --auto-aq mode is:
> 
> ```
> --aq-auto    Configure auto-AQ mode. Disabled 0 (default), <>0 enabled
>                 - Bit 1: If set to 1, enable hysteresis.
>                 - Bit 2: If set to 1, enable HDR mode => don't use biased mode on auto-AQ.
>                 - Bit 3: If set to 1, replace AQ-MODE 1 by AQ-MODE 5. Overrided by bit 2.
> ```

m-ab-s by default uses multicoreware's official bitbucket repo, so shouldn't provide any "additional functionalities"
