### ISSUE TITLE
Mod version compatible with Ryzen 7-7840HS 

### ISSUE THREAD

**Issue by madey83** [Patman86/x265-Mod-by-Patman#25]
hello,

i would like to ask what is the best version (compilation) of your last release to Ryzen 7-7840HS ?

**Comment by DJATOM** [comment]
[znver4](https://github.com/Patman86/x265-Mod-by-Patman/releases/download/3.6%2B2%2B13/x265-3.6+2+13-9a3dac6e5-.Mod-by-Patman.-x64-znver4-gcc13.2.0.7z)

**Comment by Patman86** [comment]
Thx DJATOM

**Comment by madey83** [comment]
thank you
