### ISSUE TITLE
Add SCC (screen content coding extension)

### ISSUE THREAD

**Issue by tormento** [Patman86/x265-Mod-by-Patman#26]
Please add SCC, have a look [here](https://hevc.hhi.fraunhofer.de/scc).

Have a look [here](https://forum.doom9.org/showthread.php?p=2005261#post2005261) too.

Thanks! :)

**Comment by Patman86** [comment]
I'll do that after my holiday 😉 so at the end of next week

**Comment by tormento** [comment]
Thank you. Finally some new features to play with!

**Comment by tormento** [comment]
Seems like that news are more than one.

Look [here](https://forum.doom9.org/showthread.php?p=2005216#post2005216).

**Comment by Patman86** [comment]
Done
