### ISSUE TITLE
[2.42] Does not activate parallel processes

### ISSUE THREAD

**Issue by Victory61** [Patman86/x265-Mod-by-Patman#29]
Good morning.
I just installed the new version 2.42 I did a new clean setting, and I found that parallel processes are not activated.

![Immagine 2024-09-05 181901](https://github.com/user-attachments/assets/697438d5-5105-42e7-b34c-d4a17444d054)
![Immagine 2024-09-05 181957](https://github.com/user-attachments/assets/66648338-4597-4035-ad23-081e4aa4597c)
![Screenshot (1118)](https://github.com/user-attachments/assets/5e485156-84c2-4c2e-9eae-0a393e4f60eb)

**Comment by Patman86** [comment]
I have just tested this quickly and unfortunately I cannot confirm this. For me, 3 chunks are executed.

@Dendraspis Do you have any ideas?

**Comment by Dendraspis** [comment]
Yes, I have. The first thing that came into my mind was:

***This has nothing to do with this Repository or tool!*** 

And yes, already solved here:
https://github.com/staxrip/staxrip/issues/1465

**Comment by Victory61** [comment]
I did a couple of tests and found that the problem occurs only with the file created with Iphone.
The same file in version 2.41.7 works with parallel processes. 

![Immagine 2024-09-05 195449](https://github.com/user-attachments/assets/049fe565-2b78-4336-b552-49805b07023a)
