### ISSUE TITLE
unable to open input file from VapourSynth

### ISSUE THREAD

**Issue by burgesskwan** [Patman86/x265-Mod-by-Patman#32]
vspipe "e:\1080p-x265.vpy" -c y4m - --arg ctrl=1 | "C:\Software\x265-4.0+4+2-c591f33d4-.Mod-by-Patman.-x64-alderlake-gcc14.2.0\x265" --y4m -D 10 --preset slower --crf 18.0 --qcomp 0.6 --aq-mode 3 --aq-strength 0.8 --early-skip --csv "e:\x265.log" --output "e:\x265.mkv"

Error:
x265 [FLAW]: unable to open input file <>
Error: fwrite() call failed when writing frame: 0, plane: 0, errno: 22

**Comment by Patman86** [comment]
Hi,

pls enter --input in Front of your vpy-file. My modded version support direct-input of vpy-files without vspipe.

**Comment by burgesskwan** [comment]
> Hi,
> 
> pls enter --input in Front of your vpy-file. My modded version support direct-input of vpy-files without vspipe.

I tried it before. But it still failed.

C:\Software\x265-4.0+4+2-c591f33d4-.Mod-by-Patman.-x64-alderlake-gcc14.2.0\x265 --input "e:\1080p-x265.vpy" --y4m -D 10 -P main10 -p slower --crf 18.0 --qcomp 0.6 --aq-mode 3 --aq-strength 0.8 --csv d:\265.log -o d:\265.mkv

x265 [FLAW]: unable to open input file <e:\1080p-x265.vpy>

My vpy-file as below:
import vapoursynth as vs
core = vs.core
import havsfunc as haf
import mvsfunc as mvf
from vapoursynth import core

core.num_threads = 1
core.max_cache_size = 2000

src = core.lsmas.LWLibavSource(source=r"e:\remux.mkv",fpsnum=0,fpsden=1,decoder="")

src = core.std.CropRel(src,left=0,right=0,top=0,bottom=0)

if 'ctrl' in globals() and int(ctrl) == 1:
 src = core.fmtc.bitdepth (src, bits=10)

src.set_output()

**Comment by Patman86** [comment]
Did you use one of the latest versions? I updated the GCC versions 2 days ago because of faulty libraries.

**Comment by burgesskwan** [comment]
> Did you use one of the latest versions? I updated the GCC versions 2 days ago because of faulty libraries.

Thx for ur reply Patman! But I'm using the latest version, the previous one was about libstdc++-6.dll error. May you please check my command and my vpy-file plz? I could not find any mistake but the program just didn't work properly.

**Comment by DJATOM** [comment]
> --y4m

🙂

**Comment by DJATOM** [comment]
"--y4m" basically forces x265 to evaluate input as yuv4mpeg data, which obviously not right. If you willing to use vpy input, ensure that there's no --y4m in options and input file ends with ".vpy".

**Comment by burgesskwan** [comment]
> "--y4m" basically forces x265 to evaluate input as yuv4mpeg data, which obviously not right.

Yes! It finally worked! Thanks for the helps, DJATOM and Patman! I really appreciate the mods you both made! Thank you!
