### ISSUE TITLE
404 Not Found Error Attempting to Download Release

### ISSUE THREAD

**Issue by AYColumbia** [Patman86/x265-Mod-by-Patman#35]
I tried to download via the link below and was directed to the 404 "not found" page.
https://github.com/Patman86/x265-Mod-by-Patman/releases/download/4.1%2B54%2B9/x265-4.1+54+9-0c07fe364-.Mod-by-Patman.-x64-msvc1942.7z

I tried a couple other links with the same result.  Anyone else having the same problem?

**Comment by Patman86** [comment]
Fixed!

**Comment by AYColumbia** [comment]
That was fast! Thank you. :)
