### ISSUE TITLE
Request to use "Instant" FPS in the progress information instead of average, and change calculation of ETA

### ISSUE THREAD

**Issue by ghost** [Patman86/x265-Mod-by-Patman#4]
Hi @Patman86 

I have already posted something similar @DJATOM 's repo, months ago, and I wish to repeat my request, adding some more info:

1) average FPS has a major flaw: if you suspend processing (powerful feature in Staxrip) then resume 1 hour later, the average FPS will have no meaning at all, and the ETA will be completely unrealistic! Example: I process a file, I suspend processing 5 minutes before it ends, and I resume processing 2 hours later. The ETA will show something like 1 hour or more, when it is expected to be 5 minutes.
2) average FPS vs Instant FPS can both be defended as good indicators.

My request is based on fixing the issue pointed out in (1).

The "Instant" FPS would be an average FPS calculated on a window of frames, or a number of buffers.
And the ETA will be based on that "Instant" FPS.

So in case the processing is suspended and resumed, the ETA will quickly give a more realistic reading.
I hope you may provide a solution !
Thanks!!

**Comment by Patman86** [comment]
Yes, I saw your request to DJATOM about this. I'll take a look at it and see what I can do.
