### ISSUE TITLE
Encoding get stuck at 100%

### ISSUE THREAD

**Issue by mugiwara12345** [Patman86/x265-Mod-by-Patman#6]
Sometimes my encoding gets stuck at 100%. I don't finish even after a few hours. It doesn't consume CPU power in that period. 
So I closed the encoding and checked the log file. The log file doesn't show any errors. It's just like a properly done encoded log file. 
The problem occurs when I  write a command to start another encode after finishing one. But since the first one doesn't get finished (Stuck at 100%), the second one doesn't start. :(

**Comment by Patman86** [comment]
You use StaxRip or only the x265.exe? Or an other Tool/GUI?
