### ISSUE TITLE
Lost in +patch+version etc

### ISSUE THREAD

**Issue by tormento** [Patman86/x265-Mod-by-Patman#8]
I am really confused about the +patch +version inside x265 builds.

x265-3.5+**104**+15 by _Patman_ — **yesterday**

x265-3.5+**131**-aMod by _DJATOM_ — **3 weeks ago** 

x265_r3_5_0_**103** by _jpsdr_ — **May 14**

How can we understand what is "the newest" regarding main branch, additional features, etc?

**Comment by Patman86** [comment]
Hello tormento,

I always use the master branch of x265 and there the last version is x265-3.5+104. When compiling my version I distinguish what is original and what changes are mine. X265-3.5+104 is original plus my changes +15, so my version is called x265-3.5+104+15.
