### ISSUE TITLE
indentation issue in slicetype.cpp

### ISSUE THREAD

**Issue by dreambottle** [Patman86/x265-Mod-by-Patman#9]
Hi, I noticed this weird indentation

https://github.com/Patman86/x265-Mod-by-Patman/blame/ba4e7a2cb3266d9cd59ab70ad5832d520a882254/source/encoder/slicetype.cpp#L614

Is this just an indentation errror, or a bug?

**Comment by Patman86** [comment]
Ist's just an indentation error.
